conformant = "Unsupported"
notes = """
Does not understand NoReturn or Never.
"""
output = """
specialtypes_never.py:11:8: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in <module>: argument "covariant" to TypeVar not supported yet [not-supported-yet]

T_co = TypeVar("T_co", covariant=True)
       \u001b[1m\u001b[31m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\u001b[39m\u001b[0m

specialtypes_never.py:21:8: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in func1: bad return type [bad-return-type]

        sys.exit(1)       \u001b[1m\u001b[31m~~~~~~~~~~~\u001b[39m\u001b[0m
        sys.exit(1)
\u001b[1m\u001b[31m~~~~~~~~~~~~~\u001b[39m\u001b[0m

specialtypes_never.py:68:5: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in func6: Type annotation for v1 does not match type of assignment [annotation-type-mismatch]

    v1: int = a  # OK
    \u001b[1m\u001b[31m~~\u001b[39m\u001b[0m

specialtypes_never.py:69:5: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in func6: Type annotation for v2 does not match type of assignment [annotation-type-mismatch]

    v2: str = a  # OK
    \u001b[1m\u001b[31m~~\u001b[39m\u001b[0m

specialtypes_never.py:70:5: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in func6: Type annotation for v3 does not match type of assignment [annotation-type-mismatch]

    v3: list[str] = a  # OK
    \u001b[1m\u001b[31m~~\u001b[39m\u001b[0m

specialtypes_never.py:86:5: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in func8: Type annotation for v3 does not match type of assignment [annotation-type-mismatch]

    v3: list[int] = c  # E
    \u001b[1m\u001b[31m~~\u001b[39m\u001b[0m

"""
conformance_automated = "Fail"
errors_diff = """
Line 19: Expected 1 errors
Line 105: Expected 1 errors
Line 11: Unexpected errors ['specialtypes_never.py:11:8: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in <module>: argument "covariant" to TypeVar not supported yet [not-supported-yet]']
Line 21: Unexpected errors ['specialtypes_never.py:21:8: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in func1: bad return type [bad-return-type]']
Line 68: Unexpected errors ['specialtypes_never.py:68:5: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in func6: Type annotation for v1 does not match type of assignment [annotation-type-mismatch]']
Line 69: Unexpected errors ['specialtypes_never.py:69:5: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in func6: Type annotation for v2 does not match type of assignment [annotation-type-mismatch]']
Line 70: Unexpected errors ['specialtypes_never.py:70:5: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in func6: Type annotation for v3 does not match type of assignment [annotation-type-mismatch]']
"""
